services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg curl libglib2.0-0 && rm -rf /var/lib/apt/lists/*
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 900 --timeout-graceful-shutdown 900
    envVars:
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-central-1
      - key: AWS_BUCKET
        value: misteruni